# Generated by Django 5.1.7 on 2025-06-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_info_evaluation_subject_info_is_easy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_info',
            name='short',
        ),
    ]
