# Generated by Django 5.1.7 on 2025-07-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0018_student_disliked_subjects_student_liked_subjects'),
        ('subjects', '0004_evaluationreview_evaluationmethod_review_otherreview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='upvotes',
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.review')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_form.student')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='votes',
            field=models.ManyToManyField(related_name='review_votes', through='subjects.ReviewVote', to='auth_form.student'),
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.UniqueConstraint(fields=('review', 'student'), name='unique_review_per_student'),
        ),
    ]
