# Generated by Django 5.1.7 on 2025-07-12 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_remove_review_downvotes_remove_review_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationreview',
            name='signature_condition',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='evaluationcomponent',
            name='evaluation_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='subjects.evaluationmethod'),
        ),
        migrations.AlterField(
            model_name='evaluationmethod',
            name='evaluation_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='subjects.evaluationreview'),
        ),
        migrations.AlterField(
            model_name='evaluationmethod',
            name='note',
            field=models.CharField(blank=True, help_text='additional info about this particular evaluation method.', max_length=64, null=True),
        ),
    ]
