# Generated by Django 5.1.7 on 2025-05-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrolled_subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='has_filled_form',
            field=models.BooleanField(default=False),
        ),
    ]
