# Generated by Django 5.1.7 on 2025-05-03 18:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0002_alter_user_managers_remove_student_enrolled_subjects_and_more'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='favorite_professors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passed_subjects',
            field=models.ManyToManyField(blank=True, related_name='passed_subjects', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_evaluation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_effort',
            field=models.PositiveIntegerField(help_text='Hours per week', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_track',
            field=models.CharField(blank=True, choices=[('SIIS23', 'SIIS'), ('SEIS23', 'SEIS'), ('KI23', 'KI'), ('KN23', 'KN'), ('IMB23', 'IMB'), ('PIT23', 'PIT')], max_length=20, null=True),
        ),
    ]
