# Generated by Django 5.1.7 on 2025-05-04 18:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favorite_professors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
    ]
