# Generated by Django 5.1.7 on 2025-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0005_alter_student_favorite_professors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='study_track',
            field=models.CharField(blank=True, choices=[('SIIS23', 'SIIS'), ('IE23', 'IE'), ('KI23', 'KI'), ('KN23', 'KN'), ('IMB23', 'IMB'), ('PIT23', 'PIT')], max_length=20, null=True),
        ),
    ]
