# Generated by Django 5.1.7 on 2025-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0006_alter_student_study_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='study_track',
            field=models.CharField(blank=True, choices=[('SIIS23', 'SIIS23'), ('IE23', 'IE23'), ('KI23', 'KI23'), ('KN23', 'KN23'), ('IMB23', 'IMB23'), ('PIT23', 'PIT23')], max_length=20, null=True),
        ),
    ]
