# Generated by Django 5.1.7 on 2025-06-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0007_alter_student_study_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passed_subjects_per_semester',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
