# Generated by Django 5.1.7 on 2025-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0008_student_passed_subjects_per_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='l1_credits',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='l2_credits',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='l3_credits',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_credits',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
