# Generated by Django 5.1.7 on 2025-06-01 12:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0009_student_l1_credits_student_l2_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='l1_credits',
        ),
        migrations.RemoveField(
            model_name='student',
            name='l2_credits',
        ),
        migrations.RemoveField(
            model_name='student',
            name='l3_credits',
        ),
        migrations.AddField(
            model_name='student',
            name='level_credits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
