# Generated by Django 5.1.7 on 2025-06-01 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0010_remove_student_l1_credits_remove_student_l2_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level_credits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), blank=True, null=True, size=None),
        ),
    ]
