# Generated by Django 5.1.7 on 2025-06-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0011_alter_student_level_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level_credits',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_credits',
        ),
        migrations.AddField(
            model_name='student',
            name='has_extracurricular',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
