# Generated by Django 5.1.7 on 2025-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0012_remove_student_level_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_credits',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
