# Generated by Django 5.1.7 on 2025-06-10 10:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0015_rename_preferred_evaluation_student_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assistants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
    ]
