# Generated by Django 5.1.7 on 2025-06-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0016_student_assistants'),
        ('subjects', '0002_subject_info_evaluation_subject_info_is_easy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_subjects',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_students', to='subjects.subject'),
        ),
    ]
