# Generated by Django 5.1.7 on 2025-06-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form', '0017_student_favorite_subjects'),
        ('subjects', '0002_subject_info_evaluation_subject_info_is_easy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disliked_subjects',
            field=models.ManyToManyField(blank=True, related_name='disliked_subjects', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='liked_subjects',
            field=models.ManyToManyField(blank=True, related_name='liked_subjects', to='subjects.subject'),
        ),
    ]
