# Generated by Django 5.1.7 on 2025-04-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('level', models.IntegerField()),
                ('short', models.TextField(blank=True, null=True)),
                ('prerequisite', models.TextField(blank=True, null=True)),
                ('activated', models.BooleanField()),
                ('e_2024_2025', models.IntegerField(blank=True, null=True)),
                ('e_2023_2024', models.IntegerField(blank=True, null=True)),
                ('e_2022_2023', models.IntegerField(blank=True, null=True)),
                ('mandatory', models.BooleanField()),
                ('mandatoryfor', models.JSONField(blank=True, default=list)),
                ('semester', models.IntegerField()),
                ('season', models.TextField()),
                ('electivefor', models.JSONField(blank=True, default=list)),
                ('professors', models.JSONField(blank=True, default=list)),
                ('assistants', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'subjectdata',
            },
        ),
    ]
