# Generated by Django 5.1.7 on 2025-04-18 17:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='assistants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='subject',
            name='electivefor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='subject',
            name='mandatoryfor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='subject',
            name='professors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True), size=None),
        ),
    ]
