# Generated by Django 5.1.7 on 2025-04-19 13:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_info',
            name='assistants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=None),
        ),
        migrations.AlterField(
            model_name='subject_info',
            name='elective_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=16), size=None),
        ),
        migrations.AlterField(
            model_name='subject_info',
            name='mandatory_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=16), size=None),
        ),
        migrations.AlterField(
            model_name='subject_info',
            name='professors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=None),
        ),
    ]
